-- ============================================
-- PHASE 30 - PILLAR 3: DRACONIAN ACCESS GATE
-- Migration: Enable RLS Policies on All Tables
-- ============================================
-- 
-- This migration implements strict role-based access control:
-- - Owner-only access for workspace_keys (already done in Pillar 2)
-- - Tiered read/write access for data tables
-- - Super Admin bypass capability
-- - Uniform error responses (prevent enumeration)
-- 
-- Apply with: psql <connection-string> -f supabase/migrations/20251213_enable_rls_policies.sql
-- ============================================

-- ============================================
-- HELPER FUNCTION: Get User's Workspace Role
-- ============================================

CREATE OR REPLACE FUNCTION get_user_workspace_role(
  p_user_id TEXT,
  p_workspace_id UUID
) RETURNS TEXT AS $$
DECLARE
  v_role TEXT;
BEGIN
  SELECT role INTO v_role
  FROM user_workspaces
  WHERE user_id = p_user_id
    AND workspace_id = p_workspace_id;
  
  RETURN v_role;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================
-- EMAIL_EVENTS TABLE
-- ============================================

ALTER TABLE email_events ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if any
DROP POLICY IF EXISTS email_events_read_access ON email_events;
DROP POLICY IF EXISTS email_events_write_access ON email_events;

-- Read policy: Users with any role can read their workspace data
CREATE POLICY email_events_read_access ON email_events
  FOR SELECT
  USING (
    -- Super Admin bypass
    current_setting('app.super_admin_id', true) = current_setting('request.jwt.claims', true)::json->>'sub'
    OR
    -- Standard: User has access to this workspace
    EXISTS (
      SELECT 1 FROM user_workspaces uw
      WHERE uw.workspace_id = email_events.workspace_id
        AND uw.user_id = current_setting('request.jwt.claims', true)::json->>'sub'
    )
  );

-- Write policy: Owners, admins, and members can write (not viewers)
CREATE POLICY email_events_write_access ON email_events
  FOR INSERT
  WITH CHECK (
    current_setting('app.super_admin_id', true) = current_setting('request.jwt.claims', true)::json->>'sub'
    OR
    EXISTS (
      SELECT 1 FROM user_workspaces uw
      WHERE uw.workspace_id = email_events.workspace_id
        AND uw.user_id = current_setting('request.jwt.claims', true)::json->>'sub'
        AND uw.role IN ('owner', 'admin', 'member')
    )
  );

-- ============================================
-- LLM_USAGE TABLE
-- ============================================

ALTER TABLE llm_usage ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS llm_usage_read_access ON llm_usage;
DROP POLICY IF EXISTS llm_usage_write_access ON llm_usage;

CREATE POLICY llm_usage_read_access ON llm_usage
  FOR SELECT
  USING (
    current_setting('app.super_admin_id', true) = current_setting('request.jwt.claims', true)::json->>'sub'
    OR
    EXISTS (
      SELECT 1 FROM user_workspaces uw
      WHERE uw.workspace_id = llm_usage.workspace_id
        AND uw.user_id = current_setting('request.jwt.claims', true)::json->>'sub'
    )
  );

CREATE POLICY llm_usage_write_access ON llm_usage
  FOR INSERT
  WITH CHECK (
    current_setting('app.super_admin_id', true) = current_setting('request.jwt.claims', true)::json->>'sub'
    OR
    EXISTS (
      SELECT 1 FROM user_workspaces uw
      WHERE uw.workspace_id = llm_usage.workspace_id
        AND uw.user_id = current_setting('request.jwt.claims', true)::json->>'sub'
        AND uw.role IN ('owner', 'admin', 'member')
    )
  );

-- ============================================
-- DAILY_STATS TABLE
-- ============================================

ALTER TABLE daily_stats ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS daily_stats_read_access ON daily_stats;

-- Daily stats are read-only (generated by triggers)
CREATE POLICY daily_stats_read_access ON daily_stats
  FOR SELECT
  USING (
    current_setting('app.super_admin_id', true) = current_setting('request.jwt.claims', true)::json->>'sub'
    OR
    EXISTS (
      SELECT 1 FROM user_workspaces uw
      WHERE uw.workspace_id = daily_stats.workspace_id
        AND uw.user_id = current_setting('request.jwt.claims', true)::json->>'sub'
    )
  );

-- ============================================
-- CAMPAIGNS TABLE
-- ============================================

ALTER TABLE campaigns ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS campaigns_read_access ON campaigns;
DROP POLICY IF EXISTS campaigns_write_access ON campaigns;

CREATE POLICY campaigns_read_access ON campaigns
  FOR SELECT
  USING (
    current_setting('app.super_admin_id', true) = current_setting('request.jwt.claims', true)::json->>'sub'
    OR
    EXISTS (
      SELECT 1 FROM user_workspaces uw
      WHERE uw.workspace_id::text = campaigns.workspace_id
        AND uw.user_id = current_setting('request.jwt.claims', true)::json->>'sub'
    )
  );

CREATE POLICY campaigns_write_access ON campaigns
  FOR ALL
  USING (
    current_setting('app.super_admin_id', true) = current_setting('request.jwt.claims', true)::json->>'sub'
    OR
    EXISTS (
      SELECT 1 FROM user_workspaces uw
      WHERE uw.workspace_id::text = campaigns.workspace_id
        AND uw.user_id = current_setting('request.jwt.claims', true)::json->>'sub'
        AND uw.role IN ('owner', 'admin', 'member')
    )
  )
  WITH CHECK (
    current_setting('app.super_admin_id', true) = current_setting('request.jwt.claims', true)::json->>'sub'
    OR
    EXISTS (
      SELECT 1 FROM user_workspaces uw
      WHERE uw.workspace_id::text = campaigns.workspace_id
        AND uw.user_id = current_setting('request.jwt.claims', true)::json->>'sub'
        AND uw.role IN ('owner', 'admin', 'member')
    )
  );

-- ============================================
-- WORKSPACE_INVITES TABLE
-- ============================================

ALTER TABLE workspace_invites ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS workspace_invites_read_access ON workspace_invites;
DROP POLICY IF EXISTS workspace_invites_manage_access ON workspace_invites;

-- Only owners and admins can manage invites
CREATE POLICY workspace_invites_read_access ON workspace_invites
  FOR SELECT
  USING (
    current_setting('app.super_admin_id', true) = current_setting('request.jwt.claims', true)::json->>'sub'
    OR
    EXISTS (
      SELECT 1 FROM user_workspaces uw
      WHERE uw.workspace_id = workspace_invites.workspace_id
        AND uw.user_id = current_setting('request.jwt.claims', true)::json->>'sub'
        AND uw.role IN ('owner', 'admin')
    )
  );

CREATE POLICY workspace_invites_manage_access ON workspace_invites
  FOR ALL
  USING (
    current_setting('app.super_admin_id', true) = current_setting('request.jwt.claims', true)::json->>'sub'
    OR
    EXISTS (
      SELECT 1 FROM user_workspaces uw
      WHERE uw.workspace_id = workspace_invites.workspace_id
        AND uw.user_id = current_setting('request.jwt.claims', true)::json->>'sub'
        AND uw.role IN ('owner', 'admin')
    )
  )
  WITH CHECK (
    current_setting('app.super_admin_id', true) = current_setting('request.jwt.claims', true)::json->>'sub'
    OR
    EXISTS (
      SELECT 1 FROM user_workspaces uw
      WHERE uw.workspace_id = workspace_invites.workspace_id
        AND uw.user_id = current_setting('request.jwt.claims', true)::json->>'sub'
        AND uw.role IN ('owner', 'admin')
    )
  );

-- ============================================
-- USER_WORKSPACES TABLE (Self-access only)
-- ============================================

ALTER TABLE user_workspaces ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS user_workspaces_self_access ON user_workspaces;
DROP POLICY IF EXISTS user_workspaces_admin_access ON user_workspaces;

-- Users can see their own workspace memberships
CREATE POLICY user_workspaces_self_access ON user_workspaces
  FOR SELECT
  USING (
    current_setting('app.super_admin_id', true) = current_setting('request.jwt.claims', true)::json->>'sub'
    OR
    user_id = current_setting('request.jwt.claims', true)::json->>'sub'
  );

-- Only owners and admins can manage workspace memberships
CREATE POLICY user_workspaces_admin_access ON user_workspaces
  FOR ALL
  USING (
    current_setting('app.super_admin_id', true) = current_setting('request.jwt.claims', true)::json->>'sub'
    OR
    EXISTS (
      SELECT 1 FROM user_workspaces uw
      WHERE uw.workspace_id = user_workspaces.workspace_id
        AND uw.user_id = current_setting('request.jwt.claims', true)::json->>'sub'
        AND uw.role IN ('owner', 'admin')
    )
  )
  WITH CHECK (
    current_setting('app.super_admin_id', true) = current_setting('request.jwt.claims', true)::json->>'sub'
    OR
    EXISTS (
      SELECT 1 FROM user_workspaces uw
      WHERE uw.workspace_id = user_workspaces.workspace_id
        AND uw.user_id = current_setting('request.jwt.claims', true)::json->>'sub'
        AND uw.role IN ('owner', 'admin')
    )
  );

-- ============================================
-- WORKSPACES TABLE (Admin-only management)
-- ============================================

ALTER TABLE workspaces ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS workspaces_read_access ON workspaces;
DROP POLICY IF EXISTS workspaces_manage_access ON workspaces;

-- Users can see workspaces they belong to
CREATE POLICY workspaces_read_access ON workspaces
  FOR SELECT
  USING (
    current_setting('app.super_admin_id', true) = current_setting('request.jwt.claims', true)::json->>'sub'
    OR
    EXISTS (
      SELECT 1 FROM user_workspaces uw
      WHERE uw.workspace_id = workspaces.id
        AND uw.user_id = current_setting('request.jwt.claims', true)::json->>'sub'
    )
  );

-- Only owners can manage workspace settings
CREATE POLICY workspaces_manage_access ON workspaces
  FOR ALL
  USING (
    current_setting('app.super_admin_id', true) = current_setting('request.jwt.claims', true)::json->>'sub'
    OR
    EXISTS (
      SELECT 1 FROM user_workspaces uw
      WHERE uw.workspace_id = workspaces.id
        AND uw.user_id = current_setting('request.jwt.claims', true)::json->>'sub'
        AND uw.role = 'owner'
    )
  )
  WITH CHECK (
    current_setting('app.super_admin_id', true) = current_setting('request.jwt.claims', true)::json->>'sub'
    OR
    EXISTS (
      SELECT 1 FROM user_workspaces uw
      WHERE uw.workspace_id = workspaces.id
        AND uw.user_id = current_setting('request.jwt.claims', true)::json->>'sub'
        AND uw.role = 'owner'
    )
  );

-- ============================================
-- GRANT PERMISSIONS
-- ============================================

-- Grant authenticated users access (RLS will filter)
GRANT SELECT, INSERT, UPDATE, DELETE ON email_events TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON llm_usage TO authenticated;
GRANT SELECT ON daily_stats TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON campaigns TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON workspace_invites TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON user_workspaces TO authenticated;
GRANT SELECT, UPDATE ON workspaces TO authenticated;

-- ============================================
-- COMMENTS (Documentation)
-- ============================================

COMMENT ON POLICY email_events_read_access ON email_events IS 'Allow users to read events from their workspace. Super Admin bypass enabled.';
COMMENT ON POLICY email_events_write_access ON email_events IS 'Allow owners/admins/members to write events. Viewers are read-only.';
COMMENT ON POLICY workspace_invites_manage_access ON workspace_invites IS 'Only owners and admins can manage invites. Members and viewers cannot invite.';
COMMENT ON POLICY user_workspaces_admin_access ON user_workspaces IS 'Only owners and admins can modify workspace membership.';
COMMENT ON POLICY workspaces_manage_access ON workspaces IS 'Only workspace owners can modify workspace settings. Admins are UNTRUSTED.';
